version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing mysql
      - sudo apt update -y
      - sudo apt install mysql-client-core-8.0
      - sudo apt install mysql-server -y
      - sudo service mysql start
      - sudo service mysql status
      - export DB_USERNAME1=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:303630164135:secret:rds-secret-YgafUh --query SecretString --output text | jq -r '.username')
      - export DB_PASSWORD1=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:303630164135:secret:rds-secret-YgafUh --query SecretString --output text | jq -r '.password')
      - export DB_USERNAME2=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:303630164135:secret:rds2-secret-qU5SV6 --query SecretString --output text | jq -r '.username')
      - export DB_PASSWORD2=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:303630164135:secret:rds2-secret-qU5SV6 --query SecretString --output text | jq -r '.password')
  build:
    commands:
      - echo Exporting the database...
      - mysqldump -h database-1.clo6msq4w97q.us-east-1.rds.amazonaws.com -u $DB_USERNAME1 -p$DB_PASSWORD1 mydatabase > backup.sql
      - echo Copy the database to the s3...
      - aws s3 cp backup.sql s3://sample2605/backup.sql
  post_build:
    commands:
      - echo Importing the database...
      - aws s3 cp s3://sample2605/backup.sql backup.sql
      - mysql -h database-2.clo6msq4w97q.us-east-1.rds.amazonaws.com -u $DB_USERNAME2 -p$DB_PASSWORD2 mydatabase < backup.sql
